export const FETCH_PROJECTS_REQUEST = 'FETCH_PROJECTS_REQUEST'
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS'
export const FETCH_PROJECTS_FAIL = 'FETCH_PROJECTS_FAIL'

export const FETCH_PROJECT_REQUEST = 'FETCH_PROJECT_REQUEST'
export const FETCH_PROJECT_SUCCESS = 'FETCH_PROJECT_SUCCESS'
export const FETCH_PROJECT_FAIL = 'FETCH_PROJECT_FAIL'

export const DELETE_PROJECT = 'DELETE_PROJECT'
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS'
export const DELETE_PROJECT_FAIL = 'DELETE_PROJECT_FAIL'

export const FETCH_IMAGES = 'FETCH_IMAGES'
export const FETCH_IMAGES_SUCCESS = 'FETCH_IMAGES_SUCCESS'
export const FETCH_IMAGES_FAIL = 'FETCH_IMAGES_FAIL'

export const FETCH_PRIVATES = 'FETCH_PRIVATES'
export const FETCH_PRIVATES_SUCCESS = 'RECEIVE_PRIVATE'
export const FETCH_PRIVATES_FAIL = 'RECEIVE_PRIVATE_FAIL'

export const SEND_EMAIL = 'SEND_EMAIL'
export const SEND_EMAIL_SUCCESS = 'SEND_EMAIL_SUCCESS'
export const SEND_EMAIL_FAIL = 'SEND_EMAIL_FAIL'

export const SAVE_PROJECTS = 'SAVE_PROJECTS'
export const SAVE_PROJECTS_SUCCESS = 'SAVE_PROJECTS_SUCCESS'
export const SAVE_PROJECTS_FAIL = 'SAVE_PROJECTS_FAIL'

export const INVALIDATE_CACHE = 'INVALIDATE_CACHE'
export const INVALIDATE_CACHE_SUCCESS = 'INVALIDATE_CACHE_SUCCESS'
export const INVALIDATE_CACHE_FAIL = 'INVALIDATE_CACHE_FAIL'
