export const REQUEST_PROJECTS = 'REQUEST_PROJECTS'
export const RECEIVE_PROJECTS = 'RECEIVE_PROJECTS'
export const RECEIVE_PROJECTS_FAIL = 'RECEIVE_PROJECTS_FAIL'

export const REQUEST_PROJECT = 'REQUEST_PROJECT'
export const RECEIVE_PROJECT = 'RECEIVE_PROJECT'
export const RECEIVE_PROJECT_FAIL = 'RECEIVE_PROJECT_FAIL'

export const DELETE_PROJECT = 'DELETE_PROJECT'
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS'
export const DELETE_PROJECT_FAIL = 'DELETE_PROJECT_FAIL'

export const REQUEST_IMAGES = 'REQUEST_IMAGES'
export const RECEIVE_IMAGES = 'RECEIVE_IMAGES'
export const RECEIVE_IMAGES_FAIL = 'RECEIVE_IMAGES_FAIL'

export const REQUEST_PRIVATES = 'REQUEST_PRIVATES'
export const RECEIVE_PRIVATES = 'RECEIVE_PRIVATE'
export const RECEIVE_PRIVATES_FAIL = 'RECEIVE_PRIVATE_FAIL'

export const SEND_EMAIL = 'SEND_EMAIL'
export const SEND_EMAIL_FAILED = 'SEND_EMAIL_FAILED'

export const SAVE_PROJECTS_INIT = 'SAVE_PROJECTS'
export const SAVE_PROJECTS_SUCCESS = 'SAVE_PROJECTS_SUCCESS'
export const SAVE_PROJECTS_FAIL = 'SAVE_PROJECTS_FAIL'

export const CACHE_INVALIDATED = 'CACHE_INVALIDATED'
export const CACHE_INVALIDATE = 'CACHE_INVALIDATE'
export const CACHE_INVALIDATE_FAIL = 'CACHE_INVALIDATE_FAIL'
