export const SELECT_CATEGORIES = 'SELECT_CATEGORIES'
export const SELECT_CATEGORY = 'SELECT_CATEGORY'
export const SELECT_PRODUCT = 'SELECT_PRODUCT'

export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
export const RECEIVE_PRODUCTS_FAIL = 'RECEIVE_PRODUCTS_FAIL'


