export const SELECT_CATEGORY = 'SELECT_CATEGORY'
export const SELECT_PRODUCT = 'SELECT_PRODUCT'

export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL'

export const SAVE_PRODUCT = 'SAVE_PRODUCT_INIT'
export const SAVE_PRODUCT_SUCCESS = 'SAVE_PRODUCT_SUCCESS'
export const SAVE_PRODUCT_FAIL = 'SAVE_PRODUCT_FAIL'

export const DELETE_PRODUCT = 'DELETE_PRODUCT_INIT'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL'
