export const UPDATE_SESSION = 'UPDATE_SESSION_SUCCESS'
export const UPDATE_SESSION_SUCCESS = 'UPDATE_SESSION_SUCCESS'
export const UPDATE_SESSION_FAIL = 'UPDATE_SESSION_FAIL'

export const FETCH_SESSION = 'FETCH_SESSION'
export const FETCH_SESSION_SUCCESS = 'FETCH_SESSION_SUCCESS'
export const FETCH_SESSION_FAIL = 'FETCH_SESSION_FAIL'

export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const LOGOUT = 'LOGOUT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'

export const NAVIGATE = '@@router/NAVIGATE'


