apiVersion: v1
kind: PersistentVolume
metadata:
  name: rms-pv
spec:
  capacity:
    storage: 100G
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: rms-persistent
    fsType: ext4
